### ISSUE TITLE
Understand how camera works

### ISSUE THREAD

**Issue by cardiosMircem** [cardiosMircem/flutter-first-project#1]
## Todo
- [] see Flutter docs;
- [] try to replicate something different;
- [] undestand core concepts;
